export const botoes = [
    { valor: 'C', tipo: 'limpar' },
    { valor: '( )', tipo: 'operadorEx' },
    { valor: '%', tipo: 'operadorEx' },
    { valor: '/', tipo: 'operador' },
    { valor: '7', tipo: 'numerico' },
    { valor: '8', tipo: 'numerico' },
    { valor: '9', tipo: 'numerico' },
    { valor: '*', tipo: 'operador' },
    { valor: '4', tipo: 'numerico' },
    { valor: '5', tipo: 'numerico' },
    { valor: '6', tipo: 'numerico' },
    { valor: '-', tipo: 'operador' },
    { valor: '1', tipo: 'numerico' },
    { valor: '2', tipo: 'numerico' },
    { valor: '3', tipo: 'numerico' },
    { valor: '+', tipo: 'operador' },
    { valor: '+/-', tipo: 'numericoEx' },
    { valor: '0', tipo: 'numerico' },
    { valor: '.', tipo: 'numerico' },
    { valor: '=', tipo: 'resultado' },
]
export type buttonType = {valor: string, tipo: string}